---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver:
      box: mwrock/Windows2012R2
      synced_folders:
      - ["/Users/jmery/Documents/_Accounts/AIG/", "C:\\vagrant"]
    transport:
      name: winrm
      elevated: true
      elevated_username: System
      elevated_password: null
  - name: ubuntu-14.04

suites:
  - name: chef-server
    run_list:
      - recipe[shavlik::hosts]
      - recipe[shavlik::install_chef_server]
    excludes:
      - windows-2012r2
    driver:
      vm_hostname: chef
      network:
        - ['private_network', {ip: '33.33.0.10'}]
      customize:
        memory: 2048
    attributes:
      chef_server:
        fqdn: chef
        install_dir: /tmp/

  - name: shavlik
    run_list:
      - recipe[shavlik::hosts]
      - recipe[shavlik::server]
    excludes:
      - ubuntu-14.04
    driver:
      vm_hostname: shavlik
      network:
        - ['private_network', {ip: '33.33.0.20'}]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/windows-patch-benchmark
    attributes:

  - name: unpatched
    run_list:
      - recipe[shavlik::hosts]
    excludes:
      - ubuntu-14.04
    driver:
      vm_hostname: unpatched
      network:
        - ['private_network', {ip: '33.33.0.30'}]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/windows-patch-benchmark
    attributes:
